research_task:
  description: >
    Conduct research on {topic}, using TranslationBot and SummarizationBot
    to gather and summarize information.
  expected_output: >
    A list with 10 bullet points about {topic}.
  agent: researcher
  tools:
    - TranslationBot
    - SummarizationBot

reporting_task:
  description: >
    Review the collected information and create a detailed report.
  expected_output: >
    A well-structured report formatted as markdown.
  agent: reporting_analyst
  tools:
    - SummarizationBot
